name: Update VPN Subscriptions

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-subs:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all subscriptions from 3X-UI
        run: |
          curl -sL --fail "https://158.160.191.123:2096/trjhrjfry/azuktay2rxjxfgdd" > pervii.txt || echo "Error 1"
          curl -sL --fail "https://158.160.191.123:2096/trjhrjfry/f2bx6rf8yen0r1nh" > dva.txt || echo "Error 2"
          curl -sL --fail "https://158.160.191.123:2096/trjhrjfry/ru6jy37s8tkse00q" > tri.txt || echo "Error 3"
          curl -sL --fail "https://158.160.191.123:2096/trjhrjfry/yt7f0iwub663radv" > chetiri.txt || echo "Error 4"
          curl -sL --fail "https://158.160.191.123:2096/trjhrjfry/crjlgj72x9b6tet4" > pyati.txt || echo "Error 5"
          curl -sL --fail "https://158.160.191.123:2096/trjhrjfry/mof95b5hwcgtr7re" > shesht.txt || echo "Error 6"
          curl -sL --fail "https://158.160.191.123:2096/trjhrjfry/5y4yxpf5byt1v7u8" > semi.txt || echo "Error 7"

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add *.txt
          if git diff --staged --quiet; then
            echo "Изменений в подписках нет. Всё актуально."
          else
            git commit -m "Авто-обновление всех подписок"
            # Принудительно пушим напрямую в ветку main без лишних проверок
            git push origin HEAD:main
          fi
